resources:
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml

images:
  - name: 905343638195.dkr.ecr.us-east-1.amazonaws.com/backend
    newName: 905343638195.dkr.ecr.us-east-1.amazonaws.com/backend
    newTag: v1.0

  - name: 905343638195.dkr.ecr.us-east-1.amazonaws.com/frontend
    newName: 905343638195.dkr.ecr.us-east-1.amazonaws.com/frontend
    newTag: v1.0